const CONFIG = {
    introTitle: ' Hee luuu cậu!',
    introDesc: ' Tớ có điều muốn hỏi cậu phải trả lời thật lòng nhaaa`,
    btnIntro: 'Okeee',
    title: 'Cậu thích tớ phải khum??? 😙',
    desc: 'Nếu không trả lời hoặc thoát ra tức cậu là người yêu tớ:33',
    btnYes: 'Ừ,thích cậu lắm <33',
    btnNo: 'Không, mơ à :3',
    question:'Nói cho tớ lí do vì sao cậu lại thích tớ điiii<3',
    btnReply: 'Whyyy',
    reply:' Tại vì cậu dễ thương vãi lìn<33333333',
    mess: 'Tớ  biết mà 🥰. Yêu cậu nhiều nhiều 😘😘',
    messDesc: 'I love you 3000',
    btnAccept: 'Yêu <3',
}
