const  CONFIG  =  {
    introTitle : 'Hee luu cậu!' ,
    introDesc : `Tôi có điều này muốn hỏi cậu phải trả lời thật lòng nhaaa` ,
    btnIntro : 'Okeee' ,
    title : 'Cậu thích tớ phải không ??? 😙' ,
    desc : ' Nếu không trả lời hoặc thoát ra tức là người yêu tớ: 3' ,
    btn Có : 'Thích lắm <33' ,
    btnNo : 'Không, mơ à: 3' ,
    question : 'Nói cho tớ nghe vì sao cậu thích tớ điiii <3' ,
    btnReply : 'Whyyy <3' ,
    reply : 'Tại vì cậu dễ thương vãi lìn <33333333' ,
    lộn xộn : 'Tớ biết mà 🥰. Yêu cậu nhiều 😘😘 ' ,
    messDesc : 'Tôi yêu bạn 3000' ,
    btnAccept : 'Yêu <3' ,
}
